name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 6.2.5
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework/tree/6.x
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework
funding:
  - https://github.com/sponsors/agordn52
topics:
  - micro-framework
  - framework

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter_dotenv: ^5.2.1
  nylo_support: ^6.7.0
  theme_provider: ^0.6.0
  flutter_secure_storage: ^9.2.2
  dart_console: ^4.1.1
  skeletonizer: ^1.4.1+1
  collection: ^1.18.0
  args: ^2.6.0
  dio: ^5.7.0
  recase: ^4.1.0
  error_stack: ^1.9.0
  date_field: ^5.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

flutter:

