name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 5.21.9
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework/tree/5.x
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework
funding:
  - https://github.com/sponsors/agordn52
topics:
  - micro-framework
  - framework

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_dotenv: ^5.1.0
  nylo_support: ^5.54.0
  theme_provider: ^0.6.0
  page_transition: ^2.1.0
  cli_dialog: ^0.5.0
  skeletonizer: ^1.1.0
  collection: ^1.17.1
  args: ^2.4.2
  dio: ^5.4.1
  recase: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

flutter:

